### ISSUE TITLE
Error install composer

### ISSUE THREAD

**Issue by leonardyrj** [naifalshaye/chatgpt#1]
Hello, I want to test your package, but this error is appearing

Could not find a matching version of package naif/chatgpt-nova4. Check the package spelling, your version constraint and that the package is available in a stability which matches your minimum-stability (dev).

**Comment by naifalshaye** [comment]
Hello Leonardy,

Thanks for creating the issue.

Fixed by creating the first release 1.0.0

Try now,
composer require naif/chatgpt

Thanks again.

**Comment by leonardyrj** [comment]
It worked out! Thanks

**Comment by naifalshaye** [comment]
Glad it worked..

Thanks for your response.
