### ISSUE TITLE
Failed to install the package

### ISSUE THREAD

**Issue by egantz** [naifalshaye/chatgpt#2]
![CleanShot 2023-06-23 at 01 18 10](https://github.com/naifalshaye/chatgpt/assets/4982233/51832b5b-a9ba-4ba2-810f-c243dad15deb)

I am getting this error message regarding the route - maybe a more unique name will help?

Very excited to try it out! 🔥

**Comment by naifalshaye** [comment]
Hi Eyal,

Thanks for submitting the issue, I really appreciate it.

I have removed the routes name like ->name('history') from routes. 
Also, renamed and updated the Inertia and api routes to more unique name.

Thanks again ..

**Comment by egantz** [comment]
Sick! Thanks a ton. Gonna try it shortly!

Eyal from *wilco.web*

**
