### ISSUE TITLE
Support selection of models

### ISSUE THREAD

**Issue by victorsoyvictor** [naifalshaye/chatgpt#5]
Currently Davinci is deprecated and we can no longer use the integration tool.

**Comment by naifalshaye** [comment]
Hi @victorsoyvictor Thanks for submitting the issue and creating the PR.

I updated the package and now you can select Models from a drop-down list which added in config file as

'chatgpt_models' => ['gpt-4', 'gpt-4o', 'gpt-3.5-turbo'],

Please update the package and let me know if there are any issues.

Thanks again.

**Comment by victorsoyvictor** [comment]
Hello,

I think these 'chatgpt_models' => ['gpt-4', 'gpt-4o', 'gpt-3.5-turbo'], are missing in the chatgpt-nova4.php file, could you double check?

Thanks,

**Comment by naifalshaye** [comment]
Hi @victorsoyvictor 

Done, Sorry about that.
